- name: Configure NTP and logging on all devices
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Configure NTP server
      ios_config:
        lines:
          - ntp server 192.168.1.11

    - name: Configure logging buffer
      ios_config:
        lines:
          - logging buffered 10000
